export const REVIEWS_ACTION_TYPES = {
  REVIEWS_START_LOADING: "review/REVIEWS_START_LOADING",
  REVIEWS_END_LOADING: "review/REVIEWS_END_LOADING",
  FETCH_REVIEWS: "review/FETCH_REVIEWS",
  FETCH_USER_REVIEWS: "review/FETCH_USER_REVIEWS",
  FETCH_REVIEW_CATEGORIES: "review/FETCH_REVIEW_CATEGORIES",
};
