export const REVIEWS_ACTION_TYPES = {
  REVIEWS_START_LOADING: "review/REVIEWS_START_LOADING",
  REVIEWS_END_LOADING: "review/REVIEWS_END_LOADING",
  FETCH_REVIEWS: "review/FETCH_REVIEWS",
  FETCH_USER_REVIEWS: "review/FETCH_USER_REVIEWS",
  FETCH_ONE_REVIEW: "review/FETCH_ONE_REVIEW",
  FETCH_REVIEW_CATEGORIES: "review/FETCH_REVIEW_CATEGORIES",
  LIKE_REVIEW: "review/LIKE_REVIEW",
  DELETE_REVIEW: "review/DELETE_REVIEW",
  COMMENT_REVIEW: "review/COMMENT_REVIEW",
};
